export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const RESET_CATEGORIES = 'RESET_CATEGORIES';
export const UPDATE_CATEGORIES_FAILED = 'UPDATE_CATEGORIES_FAILED';
export const UPDATE_CATEGORIES_SUCCESS = 'UPDATE_CATEGORIES_SUCCEED';

export const RESET_FORUM = 'RESET_FORUM';
export const UPDATE_FORUM = 'UPDATE_FORUM';
export const UPDATE_FORUM_FAILED = 'UPDATE_FORUM_FAILED';
export const UPDATE_FORUM_SUCCESS = 'UPDATE_FORUM_SUCCESS';

export const RESET_TOPIC = 'RESET_TOPIC';
export const UPDATE_TOPIC = 'UPDATE_TOPIC';
export const UPDATE_TOPIC_FAILED = 'UPDATE_TOPIC_FAILED';
export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS';

export const LOADING = 'LOADING';
export const LOADED = 'LOADED';
export const LOAD_FAILED = 'LOAD_FAILED';
export const NOT_LOADED = 'NOT_LOADED';

export const TOGGLE_SIDE_PANEL = 'SHOW_SIDE_PANEL';
export const CLOSE_SIDE_PANEL = 'CLOSE_SIDE_PANEL';
export const OPEN_SIDE_PANEL = 'OPEN_SIDE_PANEL';
